fdbdata = [{'code': 6, 'parent': 0, 'ispath': True, 'name': 'Зарядные устройства', 'quantity': None, 'price': None},
           {'code': 92, 'parent': 6, 'ispath': True, 'name': 'Сетевые', 'quantity': None, 'price': None},
           {'code': 96, 'parent': 92, 'ispath': True, 'name': 'Блочок', 'quantity': None, 'price': None},
           {'code': 97, 'parent': 92, 'ispath': True, 'name': 'Блочек + microUSB', 'quantity': None, 'price': None},
           {'code': 98, 'parent': 92, 'ispath': True, 'name': 'Блочок + type C', 'quantity': None, 'price': None},
           {'code': 99, 'parent': 92, 'ispath': True, 'name': 'Блочок + lightning', 'quantity': None, 'price': None},
           {'code': 100, 'parent': 92, 'ispath': True, 'name': 'Не USB зарядки', 'quantity': None, 'price': None},
           {'code': 95, 'parent': 6, 'ispath': True, 'name': 'Переходники и адаптеры', 'quantity': None, 'price': None},
           {'code': 8, 'parent': 0, 'ispath': True, 'name': 'Батареи и аккумуляторы', 'quantity': None, 'price': None},
           {'code': 3, 'parent': 8, 'ispath': True, 'name': 'Для смартфонов', 'quantity': None, 'price': None},
           {'code': 49, 'parent': 8, 'ispath': True, 'name': 'Аккумуляторы AA 18650', 'quantity': None, 'price': None},
           {'code': 4, 'parent': 8, 'ispath': True, 'name': 'Батарейки бытовые', 'quantity': None, 'price': None},
           {'code': 12, 'parent': 0, 'ispath': True, 'name': 'Смартфоны', 'quantity': None, 'price': None},
           {'code': 80, 'parent': 12, 'ispath': True, 'name': 'Samsung', 'quantity': None, 'price': None},
           {'code': 81, 'parent': 12, 'ispath': True, 'name': 'Realme / Oppo / Vivo / OnePlus', 'quantity': None,
            'price': None},
           {'code': 82, 'parent': 12, 'ispath': True, 'name': 'Xiaomi / Redmi / Poco', 'quantity': None, 'price': None},
           {'code': 83, 'parent': 12, 'ispath': True, 'name': 'Tecno / Infinix', 'quantity': None, 'price': None},
           {'code': 135, 'parent': 12, 'ispath': True, 'name': 'Umidigi / Oscal', 'quantity': None, 'price': None},
           {'code': 23, 'parent': 0, 'ispath': True, 'name': 'Наушники', 'quantity': None, 'price': None},
           {'code': 69, 'parent': 23, 'ispath': True, 'name': 'Bluetooth гарнитуры', 'quantity': None, 'price': None},
           {'code': 77, 'parent': 23, 'ispath': True, 'name': 'TWS гарнитуры', 'quantity': None, 'price': None},
           {'code': 127, 'parent': 23, 'ispath': True, 'name': 'Компьютерные с микрофоном', 'quantity': None,
            'price': None},
           {'code': 125, 'parent': 23, 'ispath': True, 'name': 'Проводные гарнитуры', 'quantity': None, 'price': None},
           {'code': 128, 'parent': 23, 'ispath': True, 'name': 'Полноразмерные Bluetooth', 'quantity': None,
            'price': None},
           {'code': 26, 'parent': 0, 'ispath': True, 'name': 'Сетевое оборудование', 'quantity': None, 'price': None},
           {'code': 28, 'parent': 0, 'ispath': True, 'name': 'Кнопочные телефоны', 'quantity': None, 'price': None},
           {'code': 29, 'parent': 0, 'ispath': True, 'name': 'Планшеты', 'quantity': None, 'price': None},
           {'code': 31, 'parent': 0, 'ispath': True, 'name': 'Кабеля и адаптеры', 'quantity': None, 'price': None},
           {'code': 118, 'parent': 31, 'ispath': True, 'name': 'TypeC - Lightning', 'quantity': None, 'price': None},
           {'code': 119, 'parent': 31, 'ispath': True, 'name': 'TypeC - TypeC', 'quantity': None, 'price': None},
           {'code': 120, 'parent': 31, 'ispath': True, 'name': 'Патч-корд', 'quantity': None, 'price': None},
           {'code': 45, 'parent': 31, 'ispath': True, 'name': 'USB - MicroUSB', 'quantity': None, 'price': None},
           {'code': 53, 'parent': 31, 'ispath': True, 'name': 'USB - TypeC', 'quantity': None, 'price': None},
           {'code': 55, 'parent': 31, 'ispath': True, 'name': 'USB - Lightning', 'quantity': None, 'price': None},
           {'code': 62, 'parent': 31, 'ispath': True, 'name': 'Аудио кабеля', 'quantity': None, 'price': None},
           {'code': 63, 'parent': 31, 'ispath': True, 'name': 'OTG TypeC 3,5mm', 'quantity': None, 'price': None},
           {'code': 78, 'parent': 31, 'ispath': True, 'name': 'Переферийные', 'quantity': None, 'price': None},
           {'code': 121, 'parent': 31, 'ispath': True, 'name': 'Магнитные', 'quantity': None, 'price': None},
           {'code': 122, 'parent': 31, 'ispath': True, 'name': 'USB - Смартчасы', 'quantity': None, 'price': None},
           {'code': 56, 'parent': 0, 'ispath': True, 'name': 'Связь - Sim карты', 'quantity': None, 'price': None},
           {'code': 54, 'parent': 0, 'ispath': True, 'name': 'Аккумуляторы Powerbank', 'quantity': None, 'price': None},
           {'code': 67, 'parent': 0, 'ispath': True, 'name': 'Портативная акустика', 'quantity': None, 'price': None},
           {'code': 76, 'parent': 0, 'ispath': True, 'name': 'Умные товары Xiaomi', 'quantity': None, 'price': None},
           {'code': 25, 'parent': 0, 'ispath': True, 'name': 'Для компьютера', 'quantity': None, 'price': None},
           {'code': 10, 'parent': 25, 'ispath': True, 'name': 'Клавиатуры', 'quantity': None, 'price': None},
           {'code': 24, 'parent': 25, 'ispath': True, 'name': 'Мыши', 'quantity': None, 'price': None},
           {'code': 88, 'parent': 24, 'ispath': True, 'name': 'Проводные', 'quantity': None, 'price': None},
           {'code': 89, 'parent': 24, 'ispath': True, 'name': 'Беспроводные', 'quantity': None, 'price': None},
           {'code': 32, 'parent': 25, 'ispath': True, 'name': 'Чистящие средства', 'quantity': None, 'price': None},
           {'code': 57, 'parent': 25, 'ispath': True, 'name': 'Коврики для мыши', 'quantity': None, 'price': None},
           {'code': 61, 'parent': 25, 'ispath': True, 'name': 'Кардридеры и USB хабы', 'quantity': None, 'price': None},
           {'code': 117, 'parent': 25, 'ispath': True, 'name': 'Клавиатура+мышь', 'quantity': None, 'price': None},
           {'code': 33, 'parent': 0, 'ispath': True, 'name': 'Авто товары', 'quantity': None, 'price': None},
           {'code': 9, 'parent': 33, 'ispath': True, 'name': 'Автомобильные ЗУ', 'quantity': None, 'price': None},
           {'code': 51, 'parent': 33, 'ispath': True, 'name': 'Автодержатели', 'quantity': None, 'price': None},
           {'code': 5, 'parent': 33, 'ispath': True, 'name': 'Видеорегистраторы', 'quantity': None, 'price': None},
           {'code': 90, 'parent': 33, 'ispath': True, 'name': 'Разветвители', 'quantity': None, 'price': None},
           {'code': 12992, 'parent': 3, 'ispath': False, 'name': 'Аккумулятор iPhone 5', 'quantity': 1.0,
            'price': 500.0},
           {'code': 15060, 'parent': 3, 'ispath': False, 'name': 'Аккумулятор Samsung G530 / G532 / J250F',
            'quantity': 1.0, 'price': 650.0},
           {'code': 15751, 'parent': 3, 'ispath': False, 'name': 'Аккумулятор Redmi 6 / 6a BN37', 'quantity': 1.0,
            'price': 800.0},
           {'code': 16247, 'parent': 3, 'ispath': False, 'name': 'Аккумулятор Redmi Note 5 BN45', 'quantity': 1.0,
            'price': 850.0},
           {'code': 16938, 'parent': 3, 'ispath': False, 'name': 'Аккумулятор iPhone 8', 'quantity': 1.0,
            'price': 1490.0},
           {'code': 16940, 'parent': 3, 'ispath': False, 'name': 'Аккумулятор Redmi 7А BN49', 'quantity': 1.0,
            'price': 800.0},
           {'code': 16941, 'parent': 3, 'ispath': False, 'name': 'Аккумулятор Redmi 8 / 8A BN51', 'quantity': 2.0,
            'price': 1000.0},
           {'code': 17026, 'parent': 3, 'ispath': False, 'name': 'Аккумулятор Redmi Go BN3A', 'quantity': 1.0,
            'price': 500.0},
           {'code': 17296, 'parent': 3, 'ispath': False, 'name': 'Аккумулятор iPhone 8 Plus', 'quantity': 1.0,
            'price': 1500.0},
           {'code': 17298, 'parent': 3, 'ispath': False, 'name': 'Аккумулятор Redmi 9A / 9C BN56', 'quantity': 1.0,
            'price': 1000.0},
           {'code': 17911, 'parent': 3, 'ispath': False, 'name': 'Аккумулятор iPhone XR', 'quantity': 1.0,
            'price': 1650.0},
           {'code': 18002, 'parent': 3, 'ispath': False, 'name': 'Аккумулятор iPhone SE 2016 HIB увеличенный 1800 mAh',
            'quantity': 1.0, 'price': 1190.0},
           {'code': 18929, 'parent': 3, 'ispath': False, 'name': 'Аккумулятор iPhone 6 HIB увеличенный 2310 mAh',
            'quantity': 1.0, 'price': 1490.0},
           {'code': 18931, 'parent': 3, 'ispath': False, 'name': 'Аккумулятор iPhone XR HIB увеличенный 3490 mAh',
            'quantity': 1.0, 'price': 2490.0},
           {'code': 10454, 'parent': 4, 'ispath': False, 'name': 'Элемент питания DURACELL LR06 AA', 'quantity': 24.0,
            'price': 75.0},
           {'code': 16025, 'parent': 4, 'ispath': False, 'name': 'Батарейка VIDEX  Lithium CR1216 BL-5',
            'quantity': 5.0, 'price': 25.0},
           {'code': 16764, 'parent': 4, 'ispath': False, 'name': 'Батарейка Xiaomi ZMI Rainbow AA', 'quantity': 22.0,
            'price': 50.0},
           {'code': 17717, 'parent': 4, 'ispath': False, 'name': 'Батарейка RENATA CR 1220', 'quantity': 9.0,
            'price': 100.0},
           {'code': 17912, 'parent': 4, 'ispath': False, 'name': 'Батарейка SAMSUNG PLEOMAX A27 BL5', 'quantity': 2.0,
            'price': 95.0},
           {'code': 18056, 'parent': 4, 'ispath': False, 'name': 'Батарейка GoPower LR6 AA BL10 Alkaline',
            'quantity': 37.0, 'price': 25.0},
           {'code': 18216, 'parent': 4, 'ispath': False, 'name': 'Батарейка GoPower LR20 D BL2 Alkaline 1.5V ',
            'quantity': 2.0, 'price': 189.0},
           {'code': 18368, 'parent': 4, 'ispath': False, 'name': 'Батарейка GoPower G13 LR44 BL10 Alkaline',
            'quantity': 20.0, 'price': 25.0},
           {'code': 18747, 'parent': 4, 'ispath': False, 'name': 'Батарейка MINAMOTO AG10 LR1130', 'quantity': 8.0,
            'price': 25.0},
           {'code': 18981, 'parent': 4, 'ispath': False, 'name': 'Батарейка GoPower CR2016 BL5 Lithium 3V',
            'quantity': 5.0, 'price': 25.0},
           {'code': 19033, 'parent': 4, 'ispath': False, 'name': 'Батарейка GoPower CR2032 BL5 Lithium 3V',
            'quantity': 10.0, 'price': 49.0},
           {'code': 19158, 'parent': 4, 'ispath': False, 'name': 'Батарейка TOSHIBA ZA 675 слух аппарат (6шт)',
            'quantity': 1.0, 'price': 395.0},
           {'code': 19160, 'parent': 4, 'ispath': False, 'name': 'Батарейка Energy Turbo LR3/ААA', 'quantity': 1.0,
            'price': 50.0},
           {'code': 19194, 'parent': 4, 'ispath': False, 'name': 'Батарейка SAMSUNG PLEOMAX LR03 Alkaline',
            'quantity': 6.0, 'price': 40.0},
           {'code': 19198, 'parent': 4, 'ispath': False, 'name': 'Батарейка крона VARTA 6F22 SUPERLIFE',
            'quantity': 1.0, 'price': 249.0},
           {'code': 19201, 'parent': 4, 'ispath': False, 'name': 'Батарейка KODAK AG4 377 LR626 LR66', 'quantity': 9.0,
            'price': 25.0},
           {'code': 19250, 'parent': 4, 'ispath': False, 'name': 'Батарейка GoPower CR2025 BL5 Lithium 3V',
            'quantity': 5.0, 'price': 25.0},
           {'code': 19327, 'parent': 4, 'ispath': False, 'name': 'Батарейка Xiaomi ZMI Rainbow AAA', 'quantity': 19.0,
            'price': 50.0},
           {'code': 19328, 'parent': 4, 'ispath': False, 'name': 'Батарейка 23A Smart Buy A23', 'quantity': 4.0,
            'price': 75.0},
           {'code': 19338, 'parent': 4, 'ispath': False, 'name': 'Батарейка ZMI Button CR2032', 'quantity': 8.0,
            'price': 100.0},
           {'code': 19521, 'parent': 4, 'ispath': False, 'name': 'Батарейка крона GoPower ULTRA 6LR61 BL1 Alkaline 9V',
            'quantity': 1.0, 'price': 299.0},
           {'code': 19568, 'parent': 4, 'ispath': False, 'name': 'Батарейка GoPower G3 LR736 LR41 392A 192 Alkaline',
            'quantity': 20.0, 'price': 20.0},
           {'code': 19199, 'parent': 5, 'ispath': False, 'name': 'Видеорегистратор HOCO DV2 Driving 1 камера чёрный',
            'quantity': 1.0, 'price': 3390.0},
           {'code': 19200, 'parent': 5, 'ispath': False, 'name': 'Видеорегистратор HOCO DV3 Driving 2 камеры чёрный',
            'quantity': 1.0, 'price': 3990.0},
           {'code': 15263, 'parent': 9, 'ispath': False, 'name': 'Автомобильное ЗУ DEFENDER UCA-12 чёрное',
            'quantity': 1.0, 'price': 199.0}, {'code': 17279, 'parent': 9, 'ispath': False,
                                               'name': 'Автомобильное ЗУ SMARTBUY NITRO, черное, 1А, 1USB + витой кабель MicroUSB',
                                               'quantity': 2.0, 'price': 279.0},
           {'code': 17620, 'parent': 9, 'ispath': False, 'name': 'Автомобильное ЗУ Xiaomi ZMI Car Charger AP821',
            'quantity': 1.0, 'price': 1199.0}, {'code': 18944, 'parent': 9, 'ispath': False,
                                                'name': 'АЗУ BOROFONE BZ18 single port QC3.0 car charger чёрное',
                                                'quantity': 4.0, 'price': 379.0},
           {'code': 18968, 'parent': 9, 'ispath': False, 'name': 'Автомобильное ЗУ Foneng C19 36W Dual QC3.0',
            'quantity': 2.0, 'price': 599.0},
           {'code': 19468, 'parent': 9, 'ispath': False, 'name': 'Автомобильное ЗУ HOCO Z46A PD20W + Type-C',
            'quantity': 1.0, 'price': 650.0},
           {'code': 12697, 'parent': 10, 'ispath': False, 'name': 'Клавиатура SmartBuy® 112 USB SBK-112U-K чёрная',
            'quantity': 1.0, 'price': 450.0},
           {'code': 14666, 'parent': 10, 'ispath': False, 'name': 'Клавиатура SmartBuy 206 чёрная', 'quantity': 1.0,
            'price': 799.0}, {'code': 19422, 'parent': 10, 'ispath': False,
                              'name': 'Клавиатура Gembird KB-8320UXL-BL проводная USB черная', 'quantity': 1.0,
                              'price': 590.0},
           {'code': 19587, 'parent': 10, 'ispath': False, 'name': 'Наклейки на клавиатуру прозрачные', 'quantity': 1.0,
            'price': 450.0},
           {'code': 12949, 'parent': 26, 'ispath': False, 'name': 'Адаптер TP-Link WN727N 150Mbps', 'quantity': 1.0,
            'price': 1090.0},
           {'code': 14714, 'parent': 26, 'ispath': False, 'name': 'Адаптер TP-Link WN722N 150Mbps', 'quantity': 1.0,
            'price': 1290.0},
           {'code': 16049, 'parent': 26, 'ispath': False, 'name': 'Роутер Xiaomi Mi Wi-Fi Router 4C R4C РСТ',
            'quantity': 1.0, 'price': 1990.0},
           {'code': 17757, 'parent': 26, 'ispath': False, 'name': 'Роутер Tenda AC6', 'quantity': 2.0, 'price': 2790.0},
           {'code': 19099, 'parent': 26, 'ispath': False, 'name': 'Роутер Tenda F3', 'quantity': 1.0, 'price': 1590.0},
           {'code': 19421, 'parent': 26, 'ispath': False, 'name': 'Адаптер TP-Link WN821N 300Mbps', 'quantity': 1.0,
            'price': 1290.0},
           {'code': 19473, 'parent': 26, 'ispath': False, 'name': 'Роутер Tenda AC5', 'quantity': 1.0, 'price': 2690.0},
           {'code': 19495, 'parent': 26, 'ispath': False, 'name': 'Роутер Digma DWR-N301', 'quantity': 2.0,
            'price': 1390.0},
           {'code': 19542, 'parent': 26, 'ispath': False, 'name': 'Роутер Tenda AC10', 'quantity': 2.0,
            'price': 3590.0},
           {'code': 19584, 'parent': 26, 'ispath': False, 'name': 'Роутер Eltex RG-1520G-Wax AX1800', 'quantity': 1.0,
            'price': 3790.0},
           {'code': 14790, 'parent': 28, 'ispath': False, 'name': 'Мобильный.телефон INOI 100 без ЗУ', 'quantity': 3.0,
            'price': 699.0},
           {'code': 17134, 'parent': 28, 'ispath': False, 'name': 'Мобильный.телефон Nokia 125 DS (TA-1253) чёрный',
            'quantity': 2.0, 'price': 2490.0},
           {'code': 19076, 'parent': 28, 'ispath': False, 'name': 'Мобильный.телефон Philips Xenium E2601 чёрный',
            'quantity': 1.0, 'price': 3490.0},
           {'code': 19257, 'parent': 28, 'ispath': False, 'name': 'Мобильный.телефон Nokia 6310 DS (TA-400) чёрный',
            'quantity': 1.0, 'price': 3190.0},
           {'code': 19375, 'parent': 28, 'ispath': False, 'name': 'Мобильный.телефон Philips Xenium X170 чёрный',
            'quantity': 8.0, 'price': 1690.0},
           {'code': 19381, 'parent': 28, 'ispath': False, 'name': 'Мобильный.телефон Philips Xenium X240 чёрный',
            'quantity': 7.0, 'price': 2690.0},
           {'code': 19483, 'parent': 28, 'ispath': False, 'name': 'Мобильный.телефон Philips Xenium X600 красный',
            'quantity': 1.0, 'price': 3490.0},
           {'code': 18979, 'parent': 29, 'ispath': False, 'name': 'Планшет INOI inoiPad 128GB Wi-Fi+LTE Space Gray',
            'quantity': 1.0, 'price': 11990.0}, {'code': 11887, 'parent': 32, 'ispath': False,
                                                 'name': 'Очиститель ЖК дисплеев Defender CLN 30598 Optima 200мл+микрофибра',
                                                 'quantity': 3.0, 'price': 220.0},
           {'code': 19506, 'parent': 32, 'ispath': False, 'name': 'Пневматический распылитель Defender 30805',
            'quantity': 2.0, 'price': 279.0},
           {'code': 15849, 'parent': 45, 'ispath': False, 'name': 'Кабель HOCO X2 MicroUSB Knitted золотой',
            'quantity': 3.0, 'price': 350.0}, {'code': 16389, 'parent': 45, 'ispath': False,
                                               'name': 'Кабель VSP microUSB 2А 1м с удлинённым коннектором чёрный',
                                               'quantity': 2.0, 'price': 289.0},
           {'code': 18823, 'parent': 45, 'ispath': False, 'name': 'Кабель USAMS US-J365 microUSB 1м 2A чёрный',
            'quantity': 1.0, 'price': 350.0},
           {'code': 18892, 'parent': 45, 'ispath': False, 'name': 'Кабель Maimi M215 MicroUSB 1м белый',
            'quantity': 1.0, 'price': 150.0},
           {'code': 18901, 'parent': 45, 'ispath': False, 'name': 'Кабель Maimi X61 MicroUSB 1,2м 6A белый',
            'quantity': 3.0, 'price': 400.0},
           {'code': 19107, 'parent': 45, 'ispath': False, 'name': 'Кабель Maimi X76 MicroUSB нейлон 25см чёрный',
            'quantity': 1.0, 'price': 150.0},
           {'code': 19308, 'parent': 45, 'ispath': False, 'name': 'Кабель LDNIO MicroUSB LS442-112 2M серый',
            'quantity': 2.0, 'price': 399.0},
           {'code': 19310, 'parent': 45, 'ispath': False, 'name': 'Кабель LDNIO MicroUSB LS362-120 2M белый',
            'quantity': 2.0, 'price': 400.0},
           {'code': 19313, 'parent': 45, 'ispath': False, 'name': 'Кабель Borofone BX87 MicroUSB 1м чёрный',
            'quantity': 2.0, 'price': 299.0},
           {'code': 19409, 'parent': 45, 'ispath': False, 'name': 'Кабель Jokade JA010 MicroUSB 1м белый',
            'quantity': 10.0, 'price': 200.0},
           {'code': 19410, 'parent': 45, 'ispath': False, 'name': 'Кабель Jokade JA010 MicroUSB 1м чёрный',
            'quantity': 7.0, 'price': 200.0},
           {'code': 19484, 'parent': 45, 'ispath': False, 'name': 'Кабель Jokade JA034 MicroUSB 1м чёрный',
            'quantity': 1.0, 'price': 400.0},
           {'code': 19606, 'parent': 45, 'ispath': False, 'name': 'Кабель Borofone BX54 microUSB нейлон 1м чёрный',
            'quantity': 8.0, 'price': 300.0},
           {'code': 13334, 'parent': 49, 'ispath': False, 'name': 'Аккумулятор ROBITON 2800mAh 18650 с защитой',
            'quantity': 1.0, 'price': 550.0},
           {'code': 18722, 'parent': 49, 'ispath': False, 'name': 'Аккумуляторы GoPower HR6 AA BL2 NI-MH 2850mAh',
            'quantity': 2.0, 'price': 699.0},
           {'code': 14783, 'parent': 51, 'ispath': False, 'name': 'Автодержатель HOCO CPH01 чёрно-синий',
            'quantity': 1.0, 'price': 250.0},
           {'code': 17611, 'parent': 51, 'ispath': False, 'name': 'Автодержатель TFN в решётку серый', 'quantity': 2.0,
            'price': 250.0}, {'code': 17966, 'parent': 51, 'ispath': False,
                              'name': 'Парковочная карта HOCO CPH19 One-click hidden signage', 'quantity': 1.0,
                              'price': 450.0},
           {'code': 18218, 'parent': 51, 'ispath': False, 'name': 'Автодержатель Borofone BH62 Bora Suction Cup чёрный',
            'quantity': 2.0, 'price': 450.0},
           {'code': 18553, 'parent': 51, 'ispath': False, 'name': 'Автодержатель HOCO CA28 Happy journey чёрный',
            'quantity': 1.0, 'price': 850.0},
           {'code': 18554, 'parent': 51, 'ispath': False, 'name': 'Автодержатель HOCO CA108 Pilot чёрный',
            'quantity': 1.0, 'price': 550.0}, {'code': 19425, 'parent': 51, 'ispath': False,
                                               'name': 'Автодержатель магнитный Borofone BH63 чёрный серебро',
                                               'quantity': 2.0, 'price': 500.0},
           {'code': 19434, 'parent': 51, 'ispath': False, 'name': 'Автодержатель магнитный More Choice C01 серебристый',
            'quantity': 1.0, 'price': 299.0},
           {'code': 19435, 'parent': 51, 'ispath': False, 'name': 'Автодержатель магнитный More Choice C01 чёрный',
            'quantity': 1.0, 'price': 299.0},
           {'code': 18895, 'parent': 53, 'ispath': False, 'name': 'Кабель Maimi X76 Type-C нейлон 25см чёрный',
            'quantity': 1.0, 'price': 150.0},
           {'code': 19311, 'parent': 53, 'ispath': False, 'name': 'Кабель LDNIO Type-C LS361-86 1M белый',
            'quantity': 4.0, 'price': 400.0},
           {'code': 19474, 'parent': 53, 'ispath': False, 'name': 'Кабель Jokade JA010 Type-C 1м белый',
            'quantity': 15.0, 'price': 250.0},
           {'code': 19475, 'parent': 53, 'ispath': False, 'name': 'Кабель Jokade JA010 Type-C 1м чёрный',
            'quantity': 17.0, 'price': 250.0},
           {'code': 19482, 'parent': 53, 'ispath': False, 'name': 'Кабель Jokade JA034 Type-C 1м чёрный',
            'quantity': 17.0, 'price': 400.0},
           {'code': 17481, 'parent': 54, 'ispath': False, 'name': 'Powerbank SOLOVE 10000mAh Type-C Чёрный',
            'quantity': 1.0, 'price': 1990.0},
           {'code': 18106, 'parent': 54, 'ispath': False, 'name': 'PowerBank XIAOMI 3 10000mAh 22,5W PB100DZM чёрный ',
            'quantity': 1.0, 'price': 1990.0},
           {'code': 18207, 'parent': 54, 'ispath': False, 'name': 'PowerBank Buro BP10G 10000mAh 2.1A синий',
            'quantity': 1.0, 'price': 1090.0},
           {'code': 18231, 'parent': 54, 'ispath': False, 'name': 'PowerBank More Choice 20000mAh PB33-20 чёрный',
            'quantity': 1.0, 'price': 1890.0},
           {'code': 18414, 'parent': 54, 'ispath': False, 'name': 'PowerBank Aspor A306 30000mAh 22.5W + 20W PD чёрный',
            'quantity': 1.0, 'price': 2690.0},
           {'code': 18494, 'parent': 54, 'ispath': False, 'name': 'PowerBank HOCO J73 30000 mAh, Powerful черный',
            'quantity': 3.0, 'price': 2790.0},
           {'code': 18691, 'parent': 54, 'ispath': False, 'name': 'PowerBank Buro BP05B 5000mAh 2.1A 2xUSB Синий',
            'quantity': 2.0, 'price': 650.0},
           {'code': 18943, 'parent': 54, 'ispath': False, 'name': 'PowerBank Xiaomi 3 PLM18ZM 20000 mAh белый',
            'quantity': 6.0, 'price': 2790.0},
           {'code': 19316, 'parent': 54, 'ispath': False, 'name': 'PowerBank Foneng P60 10000 mAh черный',
            'quantity': 1.0, 'price': 1490.0}, {'code': 19318, 'parent': 54, 'ispath': False,
                                                'name': 'PowerBank REMAX RPP-625 Ruinay Series 10000 mAh серый',
                                                'quantity': 2.0, 'price': 1490.0},
           {'code': 19325, 'parent': 54, 'ispath': False, 'name': 'PowerBank XIAOMI 3 10000mAh 22,5W PB100DZM серый',
            'quantity': 2.0, 'price': 1990.0},
           {'code': 18491, 'parent': 55, 'ispath': False, 'name': 'Кабель Xiaomi ZMI Lightning MFi AL813C 1м белый',
            'quantity': 1.0, 'price': 1190.0},
           {'code': 18958, 'parent': 55, 'ispath': False, 'name': 'Кабель Maimi X61 Lightning 1,2м 6А Белый',
            'quantity': 2.0, 'price': 400.0},
           {'code': 19259, 'parent': 55, 'ispath': False, 'name': 'Кабель HOCO X88 Lightning Gratified чёрный',
            'quantity': 4.0, 'price': 250.0},
           {'code': 19260, 'parent': 55, 'ispath': False, 'name': 'Кабель Maimi X76 Lighning нейлон 25см чёрный',
            'quantity': 1.0, 'price': 250.0},
           {'code': 19384, 'parent': 55, 'ispath': False, 'name': 'Кабель Jokade JA010 Lightning 1м белый',
            'quantity': 3.0, 'price': 150.0},
           {'code': 19485, 'parent': 55, 'ispath': False, 'name': 'Кабель Jokade JA034 Lightning 1м чёрный',
            'quantity': 15.0, 'price': 400.0},
           {'code': 12652, 'parent': 56, 'ispath': False, 'name': 'Тариф Волна Ветер (месяц оплачен)', 'quantity': 1.0,
            'price': 500.0},
           {'code': 15818, 'parent': 56, 'ispath': False, 'name': 'Тариф Win Mobile Просто', 'quantity': 1.0,
            'price': 200.0},
           {'code': 17441, 'parent': 56, 'ispath': False, 'name': 'Тариф Win Mobile Online', 'quantity': 3.0,
            'price': 200.0},
           {'code': 18437, 'parent': 56, 'ispath': False, 'name': 'Тариф Волна Сделай сам', 'quantity': 5.0,
            'price': 250.0},
           {'code': 18549, 'parent': 56, 'ispath': False, 'name': 'Тариф Волна Моя страна', 'quantity': 6.0,
            'price': 250.0},
           {'code': 18564, 'parent': 56, 'ispath': False, 'name': 'Тариф Волна Моя Волна', 'quantity': 3.0,
            'price': 300.0},
           {'code': 19494, 'parent': 56, 'ispath': False, 'name': 'Тариф Волна Моя страна супер', 'quantity': 2.0,
            'price': 250.0},
           {'code': 19061, 'parent': 57, 'ispath': False, 'name': 'Коврик для мыши VS Фауна черепаха 194x233',
            'quantity': 1.0, 'price': 200.0},
           {'code': 19569, 'parent': 57, 'ispath': False, 'name': 'Коврик для мыши Defender Wild Animals 220x180x2',
            'quantity': 1.0, 'price': 250.0},
           {'code': 19571, 'parent': 57, 'ispath': False, 'name': 'Коврик для мыши 800x300x3 мм красно-коричневый',
            'quantity': 1.0, 'price': 599.0}, {'code': 19598, 'parent': 57, 'ispath': False,
                                               'name': 'Коврик для мыши Gembird Соты 900х400х3мм ткань+резина',
                                               'quantity': 1.0, 'price': 699.0},
           {'code': 10862, 'parent': 61, 'ispath': False, 'name': 'Картридер Smartbuy SBR-717-B, голубой SBR-717-B',
            'quantity': 1.0, 'price': 279.0},
           {'code': 10863, 'parent': 61, 'ispath': False, 'name': 'Картридер Smartbuy SBR-717-R красный',
            'quantity': 1.0, 'price': 279.0},
           {'code': 19438, 'parent': 61, 'ispath': False, 'name': 'USB-HUB HOCO HB25 Easy 4 в 1 USB3.0',
            'quantity': 1.0, 'price': 899.0},
           {'code': 19502, 'parent': 61, 'ispath': False, 'name': 'USB-HUB HOCO HB1 белый', 'quantity': 1.0,
            'price': 699.0}, {'code': 11410, 'parent': 62, 'ispath': False,
                              'name': 'Аудиоудлинитель TELECOM 3.5 Jack (M) - 3.5 Jack (F) 2 м', 'quantity': 1.0,
                              'price': 220.0}, {'code': 13076, 'parent': 62, 'ispath': False,
                                                'name': 'Аудиоудлинитель TELECOM 3.5 Jack (M) - 3.5 Jack (F) 5 м',
                                                'quantity': 2.0, 'price': 300.0},
           {'code': 18124, 'parent': 62, 'ispath': False, 'name': 'Аудиокабель VCOM 3.5 Jack (M) - 2xRCA (M) 5 метров',
            'quantity': 2.0, 'price': 299.0}, {'code': 18125, 'parent': 62, 'ispath': False,
                                               'name': 'АудиокабельTelecom Pro TAV7183M-1.5M 3.5 Jack (M) - 2xRCA (M)',
                                               'quantity': 1.0, 'price': 395.0},
           {'code': 18824, 'parent': 62, 'ispath': False, 'name': 'Аудиокабель SmartBuy 3,5 Jack(M) - 2xRCA 3метра',
            'quantity': 1.0, 'price': 199.0},
           {'code': 18941, 'parent': 62, 'ispath': False, 'name': 'Кабель Exployd AUX EX-K-635', 'quantity': 2.0,
            'price': 199.0},
           {'code': 19197, 'parent': 62, 'ispath': False, 'name': 'Аудиоудлинитель 3,5mm HOCO UPA20 1м серый',
            'quantity': 1.0, 'price': 250.0},
           {'code': 19203, 'parent': 62, 'ispath': False, 'name': 'Кабель AUX HOCO UPA23 1м серый', 'quantity': 2.0,
            'price': 250.0},
           {'code': 19408, 'parent': 62, 'ispath': False, 'name': 'AUX кабель More choice UK24 нейлон 1м',
            'quantity': 5.0, 'price': 200.0},
           {'code': 77777, 'parent': 62, 'ispath': False, 'name': 'AUX color в ассортименте', 'quantity': 1.0,
            'price': 100.0},
           {'code': 15382, 'parent': 63, 'ispath': False, 'name': 'Переходник RITMIX RAS-110 (наушники+микрофон)',
            'quantity': 3.0, 'price': 150.0}, {'code': 16051, 'parent': 63, 'ispath': False,
                                               'name': 'Переходник CQL001 Lightning Aux + Lightning charge разветлитель',
                                               'quantity': 1.0, 'price': 200.0},
           {'code': 16969, 'parent': 63, 'ispath': False, 'name': 'Аудиоразветвитель RITMIX RAS-150 чёрный',
            'quantity': 1.0, 'price': 200.0},
           {'code': 17064, 'parent': 63, 'ispath': False, 'name': 'Переходник Micro to Lightning металл',
            'quantity': 2.0, 'price': 75.0}, {'code': 17532, 'parent': 63, 'ispath': False,
                                              'name': 'Адаптер Lightning - Jack 3,5mm Exployd EX-AD-756 чёрный',
                                              'quantity': 2.0, 'price': 450.0},
           {'code': 18974, 'parent': 63, 'ispath': False, 'name': 'Кабель DEFENDER OTG microUSB', 'quantity': 2.0,
            'price': 100.0},
           {'code': 19109, 'parent': 63, 'ispath': False, 'name': 'Адаптер Hoco UA17 USB(M) - Type-C(F)',
            'quantity': 3.0, 'price': 200.0},
           {'code': 19341, 'parent': 63, 'ispath': False, 'name': 'Адаптер Maimi Y9 Lightning-3.5мм белый',
            'quantity': 1.0, 'price': 399.0},
           {'code': 19481, 'parent': 63, 'ispath': False, 'name': 'OTG переходник FaizFull FP17 Type-C',
            'quantity': 3.0, 'price': 250.0},
           {'code': 19489, 'parent': 63, 'ispath': False, 'name': 'Адаптер Borofone OTG BV2 MicroUSB/USB',
            'quantity': 2.0, 'price': 200.0},
           {'code': 19524, 'parent': 63, 'ispath': False, 'name': 'Адаптер Hoco LS36 Type-C-3.5мм чёрный',
            'quantity': 3.0, 'price': 399.0},
           {'code': 345029, 'parent': 63, 'ispath': False, 'name': 'Кабель Noname OTG Mini-USB ', 'quantity': 2.0,
            'price': 140.0},
           {'code': 14707, 'parent': 67, 'ispath': False, 'name': 'Радиоприёмник RITMIX RPR-065 серый', 'quantity': 2.0,
            'price': 2490.0},
           {'code': 16268, 'parent': 67, 'ispath': False, 'name': 'Портативная BT акустика W-King K3H', 'quantity': 1.0,
            'price': 11990.0},
           {'code': 16999, 'parent': 67, 'ispath': False, 'name': 'Портативная Bluetooth колонка Borofone BR1 Чёрная',
            'quantity': 1.0, 'price': 1090.0},
           {'code': 17921, 'parent': 67, 'ispath': False, 'name': 'Радиоприёмник RITMIX RPR-102 карбон',
            'quantity': 1.0, 'price': 3890.0},
           {'code': 18220, 'parent': 67, 'ispath': False, 'name': 'Портативная Bluetooth колонка Mi Portable BHR4802GL',
            'quantity': 1.0, 'price': 2390.0},
           {'code': 18371, 'parent': 67, 'ispath': False, 'name': 'Радиоприёмник RITMIX RPR-089 коричневый',
            'quantity': 2.0, 'price': 2690.0},
           {'code': 19060, 'parent': 67, 'ispath': False, 'name': 'Радиоприёмник Hyundai H-PSR156 коричневый',
            'quantity': 2.0, 'price': 3490.0},
           {'code': 19161, 'parent': 67, 'ispath': False, 'name': 'Акустическая система 2.0 CBR CMS 635 чёрныя',
            'quantity': 1.0, 'price': 1090.0},
           {'code': 19185, 'parent': 67, 'ispath': False, 'name': 'Умная колонка Яндекс Станция Лайт мятный',
            'quantity': 1.0, 'price': 4990.0},
           {'code': 19267, 'parent': 67, 'ispath': False, 'name': 'Портативная BT акустика W-King D6', 'quantity': 1.0,
            'price': 5990.0},
           {'code': 19268, 'parent': 67, 'ispath': False, 'name': 'Портативная BT акустика W-King D120',
            'quantity': 1.0, 'price': 3990.0},
           {'code': 19269, 'parent': 67, 'ispath': False, 'name': 'Портативная BT акустика W-King D320',
            'quantity': 1.0, 'price': 6990.0},
           {'code': 19296, 'parent': 67, 'ispath': False, 'name': 'Радиоприемник Supra ST-10 черный', 'quantity': 1.0,
            'price': 1990.0}, {'code': 19405, 'parent': 67, 'ispath': False,
                               'name': 'Портативная Bluetooth колонка Borofone BR1 Бирюзовая', 'quantity': 1.0,
                               'price': 1090.0},
           {'code': 19406, 'parent': 67, 'ispath': False, 'name': 'Портативная Bluetooth колонка Borofone BR24 Чёрная',
            'quantity': 1.0, 'price': 1590.0}, {'code': 19534, 'parent': 67, 'ispath': False,
                                                'name': 'Умная колонка Яндекс Станция Мини 2.1 с часами чёрная',
                                                'quantity': 1.0, 'price': 7990.0},
           {'code': 19543, 'parent': 67, 'ispath': False, 'name': 'Умная колонка Яндекс Станция Лайт зеленая',
            'quantity': 1.0, 'price': 5990.0},
           {'code': 19544, 'parent': 67, 'ispath': False, 'name': 'Умная колонка Яндекс Станция Лайт коралловая',
            'quantity': 1.0, 'price': 5990.0},
           {'code': 19545, 'parent': 67, 'ispath': False, 'name': 'Умная колонка Яндекс Станция Лайт розовая',
            'quantity': 1.0, 'price': 5990.0},
           {'code': 19546, 'parent': 67, 'ispath': False, 'name': 'Умная колонка Яндекс Станция Лайт синяя',
            'quantity': 1.0, 'price': 5990.0}, {'code': 19555, 'parent': 67, 'ispath': False,
                                                'name': 'Умная колонка Яндекс Станция Мини 2.1 с часами серая',
                                                'quantity': 1.0, 'price': 7990.0},
           {'code': 14710, 'parent': 69, 'ispath': False, 'name': 'Bluetooth гарнитура MI Headset Black',
            'quantity': 2.0, 'price': 1190.0},
           {'code': 16978, 'parent': 69, 'ispath': False, 'name': 'Bluetooth гарнитура Mi Earphone Mini Black',
            'quantity': 1.0, 'price': 990.0},
           {'code': 16997, 'parent': 69, 'ispath': False, 'name': 'Bluetooth гарнитура Awei А850BL Черный',
            'quantity': 1.0, 'price': 750.0},
           {'code': 16074, 'parent': 76, 'ispath': False, 'name': 'Детская зубная щётка Xiaomi Dr. Bei Toothbrush',
            'quantity': 1.0, 'price': 350.0}, {'code': 16579, 'parent': 76, 'ispath': False,
                                               'name': 'Бактерицидная умная лампа Xiaomi Five Smart Sterilization Lamp',
                                               'quantity': 1.0, 'price': 3490.0},
           {'code': 16820, 'parent': 76, 'ispath': False,
            'name': 'Сменный фильтр пыли для робота-пылесоса Xiaomi Mija 1C (2шт)', 'quantity': 1.0, 'price': 450.0},
           {'code': 18256, 'parent': 76, 'ispath': False,
            'name': 'Щетка боковая сменная для Robot Vacuum cleaner (SDBS01RR)', 'quantity': 1.0, 'price': 699.0},
           {'code': 18257, 'parent': 76, 'ispath': False, 'name': 'Щетка основная сменная для Robot Vacuum cleaner',
            'quantity': 2.0, 'price': 799.0}, {'code': 18797, 'parent': 76, 'ispath': False,
                                               'name': 'Электрощётка Xiaomi Mijia Sonic Electric T100 MES603 Blue',
                                               'quantity': 1.0, 'price': 1090.0},
           {'code': 15729, 'parent': 77, 'ispath': False, 'name': 'Наушники TWS HOCO ES39 white', 'quantity': 1.0,
            'price': 1890.0},
           {'code': 18680, 'parent': 77, 'ispath': False, 'name': 'Наушники TWS Hoco EW05 Plus white', 'quantity': 1.0,
            'price': 2190.0},
           {'code': 19441, 'parent': 77, 'ispath': False, 'name': 'Наушники TWS -XO- X23 белые', 'quantity': 1.0,
            'price': 990.0},
           {'code': 19448, 'parent': 77, 'ispath': False, 'name': 'Наушники TWS HOCO EW46 True серые', 'quantity': 1.0,
            'price': 1499.0},
           {'code': 19451, 'parent': 77, 'ispath': False, 'name': 'Наушники TWS HOCO EQ1 Music guide белые',
            'quantity': 1.0, 'price': 1799.0},
           {'code': 19549, 'parent': 77, 'ispath': False, 'name': 'Наушники TWS -XO- X33 Yu Jing синие',
            'quantity': 1.0, 'price': 990.0},
           {'code': 19551, 'parent': 77, 'ispath': False, 'name': 'Наушники TWS HOCO EW75 True белые', 'quantity': 1.0,
            'price': 1790.0}, {'code': 15922, 'parent': 78, 'ispath': False,
                               'name': 'Переходник HDMI-microHDMI Gembird/Cablexpert A-HDMI-FD', 'quantity': 1.0,
                               'price': 200.0},
           {'code': 16540, 'parent': 78, 'ispath': False, 'name': 'Кабель DEFENDER M-M HDMI-05 HDMI, ver 1.4, 1.5 м',
            'quantity': 1.0, 'price': 249.0},
           {'code': 16541, 'parent': 78, 'ispath': False, 'name': 'Кабель DEFENDER M-M HDMI-07 HDMI, ver 1.4, 2 м',
            'quantity': 1.0, 'price': 399.0}, {'code': 17054, 'parent': 78, 'ispath': False,
                                               'name': 'Переходник HDMI - DVI Gembird/ Cablexpert , черный (A-HDMI-DVI-3)',
                                               'quantity': 1.0, 'price': 299.0},
           {'code': 17891, 'parent': 78, 'ispath': False, 'name': 'Кабель Smartbuy USB 2.0 AM-BM для принтера 5 м',
            'quantity': 1.0, 'price': 249.0},
           {'code': 18596, 'parent': 78, 'ispath': False, 'name': 'Кабель для принтера Telecom AM-BM 3м',
            'quantity': 2.0, 'price': 349.0},
           {'code': 18867, 'parent': 78, 'ispath': False, 'name': 'Кабель HDMI-HDMI V1.4 Exployd EX-K-1407 1м чёрный',
            'quantity': 1.0, 'price': 199.0},
           {'code': 18969, 'parent': 78, 'ispath': False, 'name': 'Кабель CC-SATA-DATA 0.5m', 'quantity': 9.0,
            'price': 100.0}, {'code': 19149, 'parent': 78, 'ispath': False,
                              'name': 'Переходник Baseus Lite Series Adapter HDMI - VGA чёрный', 'quantity': 1.0,
                              'price': 1190.0},
           {'code': 19207, 'parent': 78, 'ispath': False, 'name': 'Кабель Орбита OT-AVW60 DP-DP 1.2 1M',
            'quantity': 1.0, 'price': 380.0},
           {'code': 19504, 'parent': 78, 'ispath': False, 'name': 'Кабель DEFENDER M-M HDMI-07 HDMI, ver 1.4, 5 м',
            'quantity': 2.0, 'price': 749.0},
           {'code': 19505, 'parent': 78, 'ispath': False, 'name': 'Кабель для принтера Telecom AM-BM 1.8м',
            'quantity': 2.0, 'price': 279.0},
           {'code': 19326, 'parent': 80, 'ispath': False, 'name': 'Смартфон Samsung Galaxy A05 4/64 серебристый',
            'quantity': 2.0, 'price': 9990.0},
           {'code': 19353, 'parent': 80, 'ispath': False, 'name': 'Смартфон Samsung Galaxy A05 4/64 салатовый',
            'quantity': 1.0, 'price': 9990.0},
           {'code': 19570, 'parent': 80, 'ispath': False, 'name': 'Смартфон Samsung Galaxy S21 FE 5G 8/128 белый',
            'quantity': 1.0, 'price': 32990.0},
           {'code': 19603, 'parent': 80, 'ispath': False, 'name': 'Смартфон Samsung Galaxy A16 4G 4/128 тёмно-серый',
            'quantity': 2.0, 'price': 14990.0},
           {'code': 19604, 'parent': 80, 'ispath': False, 'name': 'Смартфон Samsung Galaxy A16 4G 4/128 светло-серый',
            'quantity': 1.0, 'price': 14990.0},
           {'code': 19168, 'parent': 81, 'ispath': False, 'name': 'Смартфон Realme Note 50 3/64 Чёрный',
            'quantity': 1.0, 'price': 7490.0},
           {'code': 19433, 'parent': 81, 'ispath': False, 'name': 'Смартфон Realme C61 6/128 зелёный', 'quantity': 2.0,
            'price': 10990.0},
           {'code': 19471, 'parent': 81, 'ispath': False, 'name': 'Смартфон Realme C61 6/128 золотой', 'quantity': 1.0,
            'price': 10990.0},
           {'code': 19597, 'parent': 81, 'ispath': False, 'name': 'Смартфон Realme Note 60x 3/64 зелёный',
            'quantity': 1.0, 'price': 6990.0},
           {'code': 18662, 'parent': 82, 'ispath': False, 'name': 'Смартфон Xiaomi Poco X5 8/256 чёрный',
            'quantity': 1.0, 'price': 21990.0},
           {'code': 19283, 'parent': 82, 'ispath': False, 'name': 'Смартфон Xiaomi Poco X6 Pro 8/256 Чёрный',
            'quantity': 1.0, 'price': 30990.0},
           {'code': 19358, 'parent': 82, 'ispath': False, 'name': 'Смартфон Xiaomi Redmi Note 13 4G 8/256 Зелёный',
            'quantity': 1.0, 'price': 16990.0},
           {'code': 19367, 'parent': 82, 'ispath': False, 'name': 'Смартфон Xiaomi 12 Lite 8/128 розовый',
            'quantity': 2.0, 'price': 20990.0},
           {'code': 19369, 'parent': 82, 'ispath': False, 'name': 'Смартфон Xiaomi Redmi 12 4/128 голубой',
            'quantity': 1.0, 'price': 11990.0},
           {'code': 19414, 'parent': 82, 'ispath': False, 'name': 'Смартфон Xiaomi Redmi A3x 3/64 чёрный',
            'quantity': 1.0, 'price': 6490.0},
           {'code': 19452, 'parent': 82, 'ispath': False, 'name': 'Смартфон Xiaomi Redmi A3x 3/64 белый',
            'quantity': 1.0, 'price': 6490.0},
           {'code': 19539, 'parent': 82, 'ispath': False, 'name': 'Смартфон Xiaomi Redmi 14C 8/256 синий',
            'quantity': 1.0, 'price': 13990.0},
           {'code': 19436, 'parent': 83, 'ispath': False, 'name': 'Смартфон Tecno Pova 6 Neo 8/128 зелёный',
            'quantity': 1.0, 'price': 15990.0},
           {'code': 19492, 'parent': 83, 'ispath': False, 'name': 'Смартфон Tecno Camon 30S 6/128 Чёрный',
            'quantity': 2.0, 'price': 15990.0},
           {'code': 19493, 'parent': 83, 'ispath': False, 'name': 'Смартфон Tecno Camon 30S 6/128 Фиолетовый',
            'quantity': 1.0, 'price': 15990.0},
           {'code': 19536, 'parent': 83, 'ispath': False, 'name': 'Смартфон Infinix Hot 50 4G 6/256 темно-серый',
            'quantity': 1.0, 'price': 14990.0},
           {'code': 19537, 'parent': 83, 'ispath': False, 'name': 'Смартфон Tecno Spark 30 8/256 чёрный',
            'quantity': 1.0, 'price': 13990.0},
           {'code': 19538, 'parent': 83, 'ispath': False, 'name': 'Смартфон Tecno Spark 30 Pro 8/128 чёрный',
            'quantity': 1.0, 'price': 15990.0},
           {'code': 19552, 'parent': 83, 'ispath': False, 'name': 'Смартфон Tecno Spark 30 8/256 белый',
            'quantity': 1.0, 'price': 13990.0},
           {'code': 19553, 'parent': 83, 'ispath': False, 'name': 'Смартфон Tecno Spark 30 Pro 8/256 белый',
            'quantity': 2.0, 'price': 17990.0},
           {'code': 19589, 'parent': 83, 'ispath': False, 'name': 'Смартфон Infinix Hot 50 4G 6/256 чёрный',
            'quantity': 1.0, 'price': 14990.0},
           {'code': 19594, 'parent': 83, 'ispath': False, 'name': 'Смартфон Tecno Spark 30 Pro 8/128 белый',
            'quantity': 2.0, 'price': 15990.0},
           {'code': 19595, 'parent': 83, 'ispath': False, 'name': 'Смартфон Tecno Spark 30 5G 6/128 Чёрный',
            'quantity': 1.0, 'price': 13990.0},
           {'code': 10313, 'parent': 88, 'ispath': False, 'name': 'Мышь проводная A4 OP-720 USB черный',
            'quantity': 1.0, 'price': 580.0},
           {'code': 19380, 'parent': 88, 'ispath': False, 'name': 'Мышь ExeGate SH-8025 чёрная', 'quantity': 1.0,
            'price': 299.0},
           {'code': 19396, 'parent': 88, 'ispath': False, 'name': 'Мышь Acer OMW136 ZL.MCEEE.01A черная',
            'quantity': 2.0, 'price': 499.0},
           {'code': 19397, 'parent': 88, 'ispath': False, 'name': 'Мышь игровая Acer Nitro OMW30 ZL.MCECC.024 черная',
            'quantity': 2.0, 'price': 1499.0},
           {'code': 19399, 'parent': 88, 'ispath': False, 'name': 'Мышь Acer OMW126 ZL.MCEEE.010 черная',
            'quantity': 2.0, 'price': 499.0},
           {'code': 19527, 'parent': 88, 'ispath': False, 'name': 'Мышь DEFENDER Optimum MB-270 чёрная',
            'quantity': 2.0, 'price': 299.0},
           {'code': 19528, 'parent': 88, 'ispath': False, 'name': 'Мышь DEFENDER Flash MB-600L', 'quantity': 2.0,
            'price': 399.0}, {'code': 17280, 'parent': 89, 'ispath': False,
                              'name': 'Беспроводная мышь Xiaomi MIIIW Wireless Office Mouse чёрная', 'quantity': 1.0,
                              'price': 1190.0},
           {'code': 17724, 'parent': 89, 'ispath': False, 'name': 'Беспроводная мышь RITMIX RMW-502 серая',
            'quantity': 1.0, 'price': 399.0}, {'code': 18744, 'parent': 89, 'ispath': False,
                                               'name': 'Беспроводная мышь Xiaomi MIIIW Wireless Office Mouse белая',
                                               'quantity': 1.0, 'price': 1190.0},
           {'code': 19113, 'parent': 89, 'ispath': False, 'name': 'Мышь беспроводная HOCO GM14 черная', 'quantity': 4.0,
            'price': 599.0},
           {'code': 19541, 'parent': 89, 'ispath': False, 'name': 'Беспроводная мышь HOCO GM28 бело-серая',
            'quantity': 2.0, 'price': 550.0},
           {'code': 19572, 'parent': 89, 'ispath': False, 'name': 'Мышь беспроводная HOCO GM21 чёрно-жёлтая',
            'quantity': 3.0, 'price': 599.0},
           {'code': 18724, 'parent': 90, 'ispath': False, 'name': 'Разветвитель прикуривателя Olesson 1634',
            'quantity': 1.0, 'price': 949.0},
           {'code': 18336, 'parent': 95, 'ispath': False, 'name': 'Переходник Евро вилка KT605 (K1616)',
            'quantity': 11.0, 'price': 150.0},
           {'code': 17548, 'parent': 96, 'ispath': False, 'name': 'СЗУ Borofone BA21A 5V/3A 1USB single port QC3 белое',
            'quantity': 5.0, 'price': 350.0},
           {'code': 18232, 'parent': 96, 'ispath': False, 'name': 'СЗУ Орбита OT-APU43 ЗУ с USB (QC3.0, 3100mA)',
            'quantity': 1.0, 'price': 649.0},
           {'code': 18677, 'parent': 96, 'ispath': False, 'name': 'СЗУ TAU13 33W USB Белый', 'quantity': 5.0,
            'price': 600.0},
           {'code': 18711, 'parent': 96, 'ispath': False, 'name': 'СЗУ 1USB 2.1A Borofone BA68A Чёрный',
            'quantity': 2.0, 'price': 200.0}, {'code': 18863, 'parent': 96, 'ispath': False,
                                               'name': 'СЗУ Borofone BA71A Power, пластик, PD20Вт, QC3.0 чёрный',
                                               'quantity': 4.0, 'price': 450.0},
           {'code': 19354, 'parent': 96, 'ispath': False, 'name': 'СЗУ Breaking WC14 USB-C PD 25W 3A Black',
            'quantity': 3.0, 'price': 790.0}, {'code': 15808, 'parent': 97, 'ispath': False,
                                               'name': 'СЗУ Borofone BA20A 2,1A  Sharp + кабель microUSB белое',
                                               'quantity': 3.0, 'price': 299.0},
           {'code': 15809, 'parent': 97, 'ispath': False,
            'name': 'СЗУ Borofone BA20A 2,1A  Sharp + кабель microUSB чёрное', 'quantity': 1.0, 'price': 299.0},
           {'code': 16945, 'parent': 97, 'ispath': False,
            'name': 'СЗУ Borofone BA21A 5V/3A 1USB Long journey QC3 + microUSB белое', 'quantity': 1.0, 'price': 500.0},
           {'code': 17852, 'parent': 97, 'ispath': False, 'name': 'СЗУ 1USB 1.0A micro USB More choice NC40m',
            'quantity': 3.0, 'price': 150.0},
           {'code': 19193, 'parent': 97, 'ispath': False, 'name': 'СЗУ Borofone BN5 QC3.0 + кабель microUSB белое',
            'quantity': 1.0, 'price': 500.0},
           {'code': 18689, 'parent': 98, 'ispath': False, 'name': 'СЗУ HOCO C109A Fighter + Type-C White',
            'quantity': 1.0, 'price': 500.0},
           {'code': 19079, 'parent': 98, 'ispath': False, 'name': 'СЗУ Xiaomi lite PD 67Вт кабель Type-C белое',
            'quantity': 1.0, 'price': 1190.0},
           {'code': 19177, 'parent': 98, 'ispath': False, 'name': 'СЗУ Xiaomi 67W GaN PD 2USB + кабель Type-C',
            'quantity': 2.0, 'price': 1790.0},
           {'code': 19263, 'parent': 98, 'ispath': False, 'name': 'СЗУ Samsung PD Type-C 45Вт + кабель Type-C Black',
            'quantity': 4.0, 'price': 850.0},
           {'code': 19372, 'parent': 98, 'ispath': False, 'name': 'СЗУ TOPOMAX TTC-F20A 18W + Type-C Голубой',
            'quantity': 1.0, 'price': 690.0},
           {'code': 19373, 'parent': 98, 'ispath': False, 'name': 'СЗУ TOPOMAX TTC-F20A 18W + Type-C Жёлтый',
            'quantity': 1.0, 'price': 690.0}, {'code': 19525, 'parent': 98, 'ispath': False,
                                               'name': 'СЗУ Maimi T101 3А QC4.0 22.5Вт + кабель Type-C белое',
                                               'quantity': 7.0, 'price': 600.0},
           {'code': 19389, 'parent': 99, 'ispath': False, 'name': 'СЗУ More Choice NC48i Lightning белое',
            'quantity': 3.0, 'price': 399.0},
           {'code': 19390, 'parent': 99, 'ispath': False, 'name': 'СЗУ More Choice NC48i Lightning чёрное',
            'quantity': 2.0, 'price': 399.0},
           {'code': 19557, 'parent': 99, 'ispath': False, 'name': 'СЗУ XO Lightning 2.4A + кабель белое',
            'quantity': 2.0, 'price': 299.0},
           {'code': 12356, 'parent': 100, 'ispath': False, 'name': 'Сзу китай Samsung C140', 'quantity': 1.0,
            'price': 149.0},
           {'code': 13170, 'parent': 100, 'ispath': False, 'name': 'СЗУ Voltz Samsung D800', 'quantity': 1.0,
            'price': 129.0},
           {'code': 19424, 'parent': 117, 'ispath': False, 'name': 'Комплект HOCO GM16 Business проводной черный',
            'quantity': 1.0, 'price': 1290.0}, {'code': 19566, 'parent': 117, 'ispath': False,
                                                'name': 'Комплект беспроводной Xiaomi Wireless Set 2 (WXJS02YM) черный',
                                                'quantity': 1.0, 'price': 2750.0},
           {'code': 19137, 'parent': 118, 'ispath': False,
            'name': 'Кабель TYPE-C - lightning HOCO X96 Hyper 1м 3A PD20Вт белый', 'quantity': 1.0, 'price': 400.0},
           {'code': 19138, 'parent': 118, 'ispath': False,
            'name': 'Кабель TYPE-C - lightning HOCO X96 Hyper 1м 3A PD20Вт чёрный', 'quantity': 6.0, 'price': 400.0},
           {'code': 19139, 'parent': 118, 'ispath': False,
            'name': 'Кабель TYPE-C - lightning HOCO X94 Leader 1м 3A PD20Вт чёрный', 'quantity': 1.0, 'price': 450.0},
           {'code': 19382, 'parent': 118, 'ispath': False,
            'name': 'Кабель TYPE-C - lightning Xiaomi (Mi) Solove DW6 1м 3A PD20Вт синий', 'quantity': 4.0,
            'price': 600.0}, {'code': 19136, 'parent': 119, 'ispath': False,
                              'name': 'Кабель HOCO X95 Goldentop Type-C - Type-C 1м 3A PD60Вт чёрный', 'quantity': 1.0,
                              'price': 400.0}, {'code': 19143, 'parent': 119, 'ispath': False,
                                                'name': 'Кабель HOCO X93 Force Type-C - Type-C 2м 5A PD240Вт белый',
                                                'quantity': 2.0, 'price': 599.0},
           {'code': 19261, 'parent': 119, 'ispath': False,
            'name': 'Кабель Borofone BX87 Type-C - Type-C 1м 3A PD60Вт чёрный', 'quantity': 1.0, 'price': 299.0},
           {'code': 19561, 'parent': 119, 'ispath': False, 'name': 'Кабель Maimi X78 Type-C-Type-C PD 65Вт 2м белый',
            'quantity': 2.0, 'price': 500.0},
           {'code': 16089, 'parent': 120, 'ispath': False, 'name': 'Патч-корд TELECOM UTP Кат. 5е серый 2 м',
            'quantity': 1.0, 'price': 99.0},
           {'code': 16409, 'parent': 120, 'ispath': False, 'name': 'Патч-корд TELECOM UTP Кат. 5е, серый, 0.5 м',
            'quantity': 4.0, 'price': 49.0},
           {'code': 16904, 'parent': 120, 'ispath': False, 'name': 'Патч-корд TELECOM UTP Кат. 5е серый 30 м',
            'quantity': 1.0, 'price': 799.0},
           {'code': 16905, 'parent': 120, 'ispath': False, 'name': 'Патч-корд TELECOM UTP Кат. 5е серый 1 м',
            'quantity': 3.0, 'price': 65.0},
           {'code': 17836, 'parent': 120, 'ispath': False, 'name': 'Патч-корд TELECOM UTP Кат. 5е серый 10 м',
            'quantity': 2.0, 'price': 499.0},
           {'code': 17843, 'parent': 120, 'ispath': False, 'name': 'Патч-корд TV-COM FTP Кат. 5е 1.5 м',
            'quantity': 3.0, 'price': 149.0},
           {'code': 18352, 'parent': 120, 'ispath': False, 'name': 'Патч-корд TELECOM UTP Кат. 5е синий 3 м',
            'quantity': 1.0, 'price': 149.0}, {'code': 15878, 'parent': 121, 'ispath': False,
                                               'name': 'Дата-кабель MRM 360 магнитный силиконовый Lightning 1м (серый)',
                                               'quantity': 1.0, 'price': 399.0},
           {'code': 14863, 'parent': 122, 'ispath': False, 'name': 'Кабель заряда Mi Band 3 чёрный', 'quantity': 1.0,
            'price': 200.0},
           {'code': 16950, 'parent': 122, 'ispath': False, 'name': 'Кабель заряда Mi Band 5 6 чёрный', 'quantity': 3.0,
            'price': 299.0},
           {'code': 15192, 'parent': 125, 'ispath': False, 'name': 'Гарнитура OXION HS230 черная', 'quantity': 4.0,
            'price': 200.0},
           {'code': 15884, 'parent': 125, 'ispath': False, 'name': 'Наушники Ear Pods Type-C белые', 'quantity': 1.0,
            'price': 799.0},
           {'code': 18506, 'parent': 125, 'ispath': False, 'name': 'Гарнитура Xiaomi Capsule Earphones DDQ01WM',
            'quantity': 1.0, 'price': 699.0},
           {'code': 18544, 'parent': 125, 'ispath': False, 'name': 'Гарнитура Exployd EX-HP-1369 Синий',
            'quantity': 3.0, 'price': 150.0},
           {'code': 18928, 'parent': 125, 'ispath': False, 'name': 'Гарнитура Xiaomi Mi Dual Driver Earphones чёрная',
            'quantity': 1.0, 'price': 990.0},
           {'code': 18951, 'parent': 125, 'ispath': False, 'name': 'Гарнитура HOCO M101 Pro Crystal sound чёрная',
            'quantity': 5.0, 'price': 350.0},
           {'code': 19392, 'parent': 125, 'ispath': False, 'name': 'Гарнитура Exployd EX-HP-1370 красная',
            'quantity': 3.0, 'price': 150.0},
           {'code': 19412, 'parent': 125, 'ispath': False, 'name': 'Наушники Panasonic RP-HJE125E-W белые',
            'quantity': 2.0, 'price': 1099.0},
           {'code': 19456, 'parent': 125, 'ispath': False, 'name': 'Наушники Jokade JD051 чёрные', 'quantity': 1.0,
            'price': 200.0},
           {'code': 19457, 'parent': 125, 'ispath': False, 'name': 'Наушники Jokade JD051 белые', 'quantity': 2.0,
            'price': 200.0},
           {'code': 19458, 'parent': 125, 'ispath': False, 'name': 'Гарнитура HOCO M124 чёрная', 'quantity': 2.0,
            'price': 250.0},
           {'code': 19459, 'parent': 125, 'ispath': False, 'name': 'Гарнитура HOCO M70 чёрная', 'quantity': 1.0,
            'price': 400.0},
           {'code': 19467, 'parent': 125, 'ispath': False, 'name': 'Гарнитура HOCO M101 Pro Crystal sound белая',
            'quantity': 4.0, 'price': 350.0},
           {'code': 800207, 'parent': 125, 'ispath': False, 'name': 'Наушники Panasonic RP-HJE 118 GUK черные',
            'quantity': 1.0, 'price': 1299.0},
           {'code': 17959, 'parent': 127, 'ispath': False, 'name': 'Гарнитура HOCO W105 Joyful gaming красные',
            'quantity': 1.0, 'price': 1290.0},
           {'code': 18366, 'parent': 127, 'ispath': False, 'name': 'Гарнитура HOCO W103 Magic с микрофоном красные',
            'quantity': 1.0, 'price': 990.0},
           {'code': 18377, 'parent': 127, 'ispath': False, 'name': 'Гарнитура Defender Warhead G-370 черный/красный',
            'quantity': 1.0, 'price': 1390.0},
           {'code': 19187, 'parent': 127, 'ispath': False, 'name': 'Гарнитура HAVIT HV-H139d', 'quantity': 1.0,
            'price': 1199.0},
           {'code': 19188, 'parent': 127, 'ispath': False, 'name': 'Гарнитура HAVIT HV-H2116d Gaming Черно-красная',
            'quantity': 1.0, 'price': 1290.0},
           {'code': 16467, 'parent': 128, 'ispath': False, 'name': 'Беспроводные BT наушники Borofone BO5 чёрные',
            'quantity': 1.0, 'price': 799.0},
           {'code': 17790, 'parent': 128, 'ispath': False, 'name': 'Беспроводные BT наушники HOCO W25 Promise Красные',
            'quantity': 1.0, 'price': 1190.0},
           {'code': 19239, 'parent': 128, 'ispath': False, 'name': 'Беспроводные BT наушники Apple EarPods 1:1 Черные',
            'quantity': 1.0, 'price': 2190.0},
           {'code': 19588, 'parent': 128, 'ispath': False, 'name': 'Беспроводные BT наушники HOCO W54 Young ANC чёрные',
            'quantity': 1.0, 'price': 2290.0},
           {'code': 19470, 'parent': 135, 'ispath': False, 'name': 'Смартфон Oscal Tiger 12 8/128 фиолетовый',
            'quantity': 1.0, 'price': 13990.0},
           {'code': 19573, 'parent': 135, 'ispath': False, 'name': 'Смартфон Umidigi A15 8/256 фиолетовый',
            'quantity': 1.0, 'price': 9990.0}]
